language: ruby
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgmp-dev
rvm:
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - "2.0.0-p648"
  - "2.1.10"
  - "2.2.4"
  - "2.3.0"
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
