name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        ruby:
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - 'jruby-9.2'
          - 'jruby-9.3'
          - 'truffleruby'
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test

