name: testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        os: [ubuntu]
        ruby-version:
          - 2.3
          - 2.4
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
          - jruby
          - truffleruby
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
